enum OrderStatus {
    PAYMENT_PENDING= 'PAYMENT_PENDING',
    PENDING='PENDING',
    IN_PROGRESS='IN_PROGRESS',
    COMPLETED='COMPLETED',
    REJECTED='REJECTED',
    CANCELLED='CANCELLED',
    REFUNDED='REFUNDED',
    ERROR='ERROR',
    PROGRESS_ERROR='PROGRESS_ERROR',
    FAILED='FAILED',
  }

export { OrderStatus }
  